#!/bin/bash
# Dynamic shell color exports - Generated by rswall
# Source this file in your .bashrc or .zshrc to apply colors to prompts

# Base16 color exports
export BASE16_COLOR_00="{{ colors.0 }}"
export BASE16_COLOR_01="{{ colors.1 }}"
export BASE16_COLOR_02="{{ colors.2 }}"
export BASE16_COLOR_03="{{ colors.3 }}"
export BASE16_COLOR_04="{{ colors.4 }}"
export BASE16_COLOR_05="{{ colors.5 }}"
export BASE16_COLOR_06="{{ colors.6 }}"
export BASE16_COLOR_07="{{ colors.7 }}"
export BASE16_COLOR_08="{{ colors.8 }}"
export BASE16_COLOR_09="{{ colors.9 }}"
export BASE16_COLOR_0A="{{ colors.10 }}"
export BASE16_COLOR_0B="{{ colors.11 }}"
export BASE16_COLOR_0C="{{ colors.12 }}"
export BASE16_COLOR_0D="{{ colors.13 }}"
export BASE16_COLOR_0E="{{ colors.14 }}"
export BASE16_COLOR_0F="{{ colors.15 }}"

# Spaceship prompt colors
export SPACESHIP_CHAR_COLOR="{{ accent }}"
export SPACESHIP_TIME_COLOR="{{ secondary }}"
export SPACESHIP_USER_COLOR="{{ colors.4 }}"
export SPACESHIP_HOST_COLOR="{{ colors.5 }}"
export SPACESHIP_DIR_COLOR="{{ colors.6 }}"
export SPACESHIP_GIT_BRANCH_COLOR="{{ colors.2 }}"
export SPACESHIP_GIT_STATUS_COLOR="{{ colors.3 }}"
export SPACESHIP_EXEC_TIME_COLOR="{{ colors.11 }}"
export SPACESHIP_EXIT_CODE_COLOR="{{ error }}"

# FZF colors
export FZF_DEFAULT_OPTS="--color=bg+:{{ surface }},bg:{{ background }},spinner:{{ accent }},hl:{{ colors.4 }},fg:{{ foreground }},header:{{ colors.4 }},info:{{ colors.3 }},pointer:{{ accent }},marker:{{ accent }},fg+:{{ foreground }},prompt:{{ colors.5 }},hl+:{{ colors.4 }}"